### ISSUE TITLE
Server crashing on Paper 1.17.1

### ISSUE THREAD

**Issue by DarkKingKaanMC** [LOOHP/InteractionVisualizer#64]
I have opened an issue on Paper (https://github.com/PaperMC/Paper/issues/6212) and one of the developers suggested your plugin might be doing some weird things with chunks. Could you take a look? The errors and all the things needed are pasted in the Paper Issue. Thanks!

**Comment by DarkKingKaanMC** [comment]
Removing the plugin from the server gets rid of the crashes. I'll just wait for a fix before I try putting it back in.

**Comment by LOOHP** [comment]
Should be fixed in 1.16.3.1, please give it a try :)

**Comment by DarkKingKaanMC** [comment]
Sure, I'll give it a try and I'll let you know how it goes tomorrow! Thanks for fixing it so quickly!

**Comment by DarkKingKaanMC** [comment]
> Should be fixed in 1.16.3.1, please give it a try :)

No, it doesn't fix the issue at all. Now the server crashes right on load, chunks get corrupted and load very slow.

**Comment by LOOHP** [comment]
Can you show the error messages?

**Comment by DarkKingKaanMC** [comment]
Yeah, here: https://pastebin.com/cJ25rMtU

**Comment by LOOHP** [comment]
The errors are a bit different this time. InteractionVisualizer is not within the stacktrace of the crash like the one you've reported in PaperMC.
Are you testing with a fresh new world? If not, can you see if it works in a fresh new world?

**Comment by DarkKingKaanMC** [comment]
The error only occured with the plugin installed. I don't think I can reproduce the issue on my own, since in only happened with a few players online casually trying to play. I might be able to. I'll see.

**Comment by DarkKingKaanMC** [comment]
I'm testing on a world that has been generated half on 1.16 and half on 1.17.

**Comment by LOOHP** [comment]
The chunk coordinate 347,-594 is mentioned in the crash report, maybe there's something specific at that location?

**Comment by LOOHP** [comment]
Also the "grave"plugin is still mentioned in the crash stacktrace. Maybe it's also related to that plugin?

**Comment by DarkKingKaanMC** [comment]
> Also the "grave" plugin is still mentioned in the new crash stacktrace. Maybe it's also related to that plugin?

It might be as well, yeah, I'll take a look.
